config/routes.rb
Rails.application.routes.draw do

  resources :cart_items
  resources :carts, only: [:destroy,:index]
  resources :items
  resources :users do
    post 'make_admin', on: :collection
    post 'make_customer', on: :collection
  end
  resources :sessions

  root 'items#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :cart_items
  has_many :items, through: :cart_items

  def cart_total
    running_total = 0
    self.cart_items.each do |item|
      running_total += item.total_price
    end
    return running_total
  end

end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :item
  has_one :user, through: :cart

  def total_price
    return self.item.price * self.quantity
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_many :users, through: :carts

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 0}
  validates :description, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0}
  validates :picture_url, presence: true
  validates :upc, presence: true

  def formatted_price
    return '%.2f' % self.price
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_one :cart
  has_many :cart_items, through: :cart
  has_many :items, through: :cart_items
  before_save :check_admin

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  def is_admin?
    return self.user_type == 1
  end

  private

  def check_admin
    self.user_type = 0 if self.user_type.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def create
    p cart_item_params.inspect
    if !authenticated?
      redirect_to root_path
    end
    new_item = CartItem.new(cart_item_params)
    new_item.cart_id = Cart.find_by(user_id: current_user.id).id
    new_item.save
    if request.xhr?
      render json: current_user.cart_items.count
    else
      redirect_to item_path(new_item.item)
    end
  end



  def update
    cart_item = CartItem.find_by(item_id: params[:id], cart_id: user_cart_id)
    cart_item.update(quantity: params[:qty])
    if request.xhr?
      render json: cart_item.quantity
    else
      redirect back
    end
  end

  def destroy
    cart_item = CartItem.find_by(item_id: params[:id], cart_id: user_cart_id)
    cart_item.destroy
    if request.xhr?
      render json: {id: cart_item.item.id, count: current_user.cart_items.count}
    else
      redirect back
    end
  end


  private

    def cart_item_params
      params.require(:cart_item).permit(:cart_id,:item_id,:quantity,:cart,:item)
    end

    def user_cart_id
      Cart.find_or_create_by(user_id: current_user.id).id
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    # render 'cart_items/_show', layout: false
    render partial: "cart_items/show"
  end

  def destroy
    cart = Cart.find(params[:id])
    cart.cart_items.each do |item|
      item.destroy
    end
    if request.xhr?
      render nothing: true
    else
      redirect_to root_path
    end
  end


end

app/controllers/items_controller.rb
include UsersHelper

class ItemsController < ApplicationController
  before_action :check_permissions, except: [:index, :show]

  def index
    @items = Item.order(:created_at)
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to @item
    else
      render 'new'
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to @item
    else
      render 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  private
  def item_params
    params.require(:item).permit(:name, :description, :quantity, :picture_url, :upc, :price)
  end
end

app/controllers/sessions_controller.rb
include UsersHelper

class SessionsController < ApplicationController
  def new
    if authenticated?
      redirect_to '/'
    else
      render 'new'
    end
  end

  def create
    p "params @create: email:#{params["email"]}, pwd:#{params["password_plaintext"]} "
    @user = User.find_by_email(params["email"])
    p "*" * 40
    p "A user #{User.first}"
    p "#" * 40
    p @user
    if @user && @user.authenticate(params["password_plaintext"])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      session.delete(:user_id)
      @error = "Please check your email address and password and try again. User: #{@user} \n password #{params["password_plaintext"]}"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
include UsersHelper

class UsersController < ApplicationController
  before_action :check_permissions, except: [:index, :show, :new, :create]

  def index
    redirect_to '/' unless current_user && current_user.is_admin?
    @users = User.order(:created_at)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
    redirect_to '/' unless current_user && current_user == @user
  end

  def create
    p "params @create: #{params.inspect} "
    @user = User.new(user_params)
    @user.password = params[:password_plaintext]
    p "-" * 40
    p @user
    p "-" * 40
    if @user.save
      Cart.create(user_id: @user.id)
      session[:user_id] = @user.id
      redirect_to '/'
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    redirect_to '/' unless current_user && current_user == @user
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def make_admin
    redirect_to '/' unless current_user && current_user.is_admin?
    @user = User.find(params[:id])
    @user.update(user_type: 1)
    redirect_to users_path
  end

  def make_customer
    redirect_to '/' unless current_user && current_user.is_admin?
    @user = User.find(params[:id])
    @user.update(user_type: 0)
    redirect_to users_path
  end

  def destroy
    redirect_to '/' unless current_user && current_user.is_admin?
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:firstname, :lastname, :email,)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def authenticated?
    return !session[:user_id].nil?
  end

  def current_user
    return User.find_by_id(session[:user_id]) if authenticated?
  end

  def check_permissions
    if !current_user
      flash[:error] = "You must log in to complete that action."
    elsif !current_user.is_admin?
      flash[:error] = "You are not authorized to complete that action."
    end
    redirect_to new_session_url unless (current_user && current_user.is_admin?)
  end
end

app/views/cart_items/_show.html.erb
<table id='shopping-cart'>
  <th>Item Name</th>
  <th>Number Ordered</th>
  <th>Price Each</th>
  <th>Total Price</th>
  <th>Remove</th>
  <% current_user.cart_items.each do |cart_item| %>
    <% item = cart_item.item %>
    <%= render partial: "items/cart_item", locals: {cart_item: cart_item, item: item} %>
  <% end %>
<tr>
  <td id='checkout' colspan='2'><%= link_to 'Checkout', cart_path(current_user.cart), method: :delete %></td>
  <td colspan='2'>Total Price: <%= current_user.cart.cart_total %></td>
  <td></td>
</tr>
</table>

app/views/items/_cart_item.html.erb
<%= puts "testing this partial" %>
<tr id="<%= item.id %>" class='cart_row'>
      <td><strong><%= item.name %></strong></td>
      <td><strong>
        <div class="dropdown">
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            <%= cart_item.quantity %>
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu">
            <% n = 1 %>
            <% item.quantity.times do %>
              <li><a href="/cart_items/<%= item.id %>?qty=<%= n %>" class='qty'><%= n %></a></li>
              <% n += 1 %>
            <% end %>
          </ul>
        </div>
      </strong></td>
      <td><strong><%= item.formatted_price %></strong></td>
      <td><strong><%= cart_item.total_price %></strong></td>
      <td>
        <a href="/cart_items/<%= item.id %>" class='remove-button'>
          <button id='remove-button' type="button" class="btn btn-sm" aria-label="Left Align">
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          </button>
        </a>
      </td>
    </tr>

app/views/items/_form.html.erb
<%= form_for :item, url: items_path, html: {:class => 'form-horizontal'} do |f| %>
<fieldset>
<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="name">Item Name</label>
  <div class="col-md-6">
  <input id="name" name="item[name]" type="text" placeholder="Steve Jobs' Turtleneck" value="<%= @item.try(:name) %>" class="form-control input-md" required="">

  </div>
</div>

<!-- Prepended text-->
<div class="form-group">
  <label class="col-md-4 control-label" for="price">Price</label>
  <div class="col-md-6">
    <div class="input-group">
      <span class="input-group-addon">$</span>
      <input id="price" name="item[price]" class="form-control" placeholder="5.00" value="<%= @item.formatted_price unless @item.price.nil? %>" type="text" required="">
    </div>

  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="quantity">Quantity</label>
  <div class="col-md-6">
  <input id="quantity" name="item[quantity]" type="text" placeholder="1" value="<%= @item.try(:quantity) %>" class="form-control input-md" required="">

  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="picture_url">Image URL</label>
  <div class="col-md-6">
  <input id="picture_url" name="item[picture_url]" type="text" placeholder="http://i.imgur.com/Ad420.png" value="<%= @item.try(:picture_url) %>" class="form-control input-md" required="">

  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="upc">UPC</label>
  <div class="col-md-6">
  <input id="upc" name="item[upc]" type="text" placeholder="R2050202929" value="<%= @item.try(:upc) %>" class="form-control input-md" required="">

  </div>
</div>

<!-- Textarea -->
<div class="form-group">
  <label class="col-md-4 control-label" for="description">Description</label>
  <div class="col-md-6">
    <textarea class="form-control" id="description" name="item[description]" rows="20"><%= @item.try(:description) %></textarea>
  </div>
</div>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label" for="submit"></label>
  <div class="col-md-4">
    <button id="submit" name="submit" class="btn btn-primary">Save</button>
  </div>
</div>

</fieldset>
<% end %>

app/views/items/edit.html.erb
<div class="container">
  <% if @item.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h3>
    </div>
    <div class="panel-body">
      <%= @item.errors.full_messages.join(", ") %>
    </div>
  </div>
  <% end %>
  <legend>Edit item</legend>
  <%= render 'items/form' %>
</div>

app/views/items/index.html.erb
<div class="container">
   <center>
    <div class="jumbotron">
      <div class="container">
        <h1>Shoppe</h1>
        <h5>We have everything you'll ever need. Except chocolate.</h5>
      </div>
    </div>
    <div class="page-header">
      <h1>All items for sale</h1>
    </div>
    <div class="row">
      <% @items.each do |item| %>
      <div class="col-xs-12 col-md-4">
        <%= link_to image_tag(item.picture_url, :height => "175px", :style => "border-radius: 50%"), item_path(item) %>
        <h5><%= link_to "#{item.name}", item_path(item) %></h5>
        <p>Price: $<%= item.formatted_price %></p>
        <% if current_user && current_user.is_admin? %>
        <p><%= link_to 'Edit', edit_item_path(item) %></p>
        <p><%= link_to 'Delete', item_path(item), method: :delete, data: { confirm: 'Are you sure?' } %></p>
        <% end %>
        <hr>
      </div>
      <% end %>
      <hr>
    </div>
  </center>
</div>

app/views/items/new.html.erb
<div class="container">
  <% if @item.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h3>
    </div>
    <div class="panel-body">
      <%= @item.errors.full_messages.join(", ") %>
    </div>
  </div>
  <% end %>
  <legend>Add a new item</legend>
  <%= render 'items/form' %>
</div>

app/views/items/show.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @item.name %></h3>
    </div>
    <div class="panel-body">
      <img src="<%= @item.picture_url %>" title="<%= @item.name %>" style="float: right; margin-left: 50px; border-radius: 5%">
      <p><strong>Price:</strong> $<%= @item.formatted_price %></p>
      <p><strong>In stock:</strong> <%= @item.quantity %></p>
      <p><strong>UPC:</strong> <%= @item.upc.upcase %></p>
      <p><strong>Description:</strong></p>
      <p><%= @item.description %></p>

      <%= form_for :cart_item, url: cart_items_path do |f| %>
        <%= f.hidden_field :item_id, :value => @item.id %>
        <%= f.select :quantity, (1..@item.quantity) %>
        <%= f.submit "Buy Now" %>
      <% end %>
    </div>
    <div class="panel-footer"><%= link_to 'Back', items_path %></div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Shoppe</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if authenticated? && current_user.is_admin? %>
          <li><a href="/users/<%= current_user.id %>">Welcome <%= current_user.email %></a></li>
          <li><%= link_to 'Add an item', new_item_path %></li>
          <li><%= link_to 'View User List', users_path %> </li>
          <li><%= link_to 'Logout', session_path(session), method: :delete %></li>
        <% elsif authenticated? %>
          <li><a href="/users/<%= current_user.id %>">Welcome <%= current_user.email %></a></li>
          <!-- Add ERB to count items in cart in Cart Button-->
          <!-- Also, add functionality so that button directs to cart view -->
          <li>
            <button type="button" class="btn btn-default btn-lg" aria-label="Left Align" data-toggle="modal" data-target="#cart-form" >
              <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true" id='cart-item-count'> <%= current_user.cart_items.length %>
              </span>
            </button>
          </li>
          <li><%= link_to 'Logout', session_path(session), method: :delete %></li>
        <% else %>
          <li><a href="" data-toggle="modal" data-target="#login-form">Login</a></li>
          <!-- <li><%= link_to 'Login', new_session_path %></li> -->
          <li><%= link_to 'Register', new_user_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav><!-- .navbar-default -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoppe</title>
  <script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= javascript_include_tag 'application'  %>
  <%= javascript_include_tag '/our_js' %>


  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag "application" %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<%= render 'layouts/nav' %>
<body>
  <% if flash[:notice] %>
    <center>
      <div class="alert alert-info" data-dismiss="alert" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
    </center>
  <% end %>
  <% if flash[:error] %>
    <center>
      <div class="alert alert-danger" data-dismiss="alert" role="alert">
        <%= flash[:error] %>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </div>
    </center>
  <% end %>
  <% if flash[:success] %>
    <center>
      <div class="alert alert-success" data-dismiss="alert" role="alert">
        <%= flash[:success] %>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </div>
    </center>
  <% end %>
<%= yield %>

<div class="modal fade" id="login-form" tabindex="-1" role="dialog" aria-labelledby="login-form">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <center><h4 class="modal-title">Login</h4></center>
      </div>
      <div class="modal-body">
        <%= render 'sessions/form' %>
      </div>
    </div>
  </div>
</div>

<% if authenticated? %>
  <div class="modal fade" id="cart-form" tabindex="-1" role="dialog" aria-labelledby="cart-form">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <center><h4 class="modal-title">Your Cart:</h4></center>
        </div>
        <div class="modal-body">
          <%= render 'cart_items/show' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for :user, url: users_path, html: {:class => 'form-horizontal'}  do |f| %>
  <fieldset>
  <!-- Text input-->
  <div class="form-group">
    <label class="col-md-4 control-label" for="firstname">First Name</label>
    <div class="col-md-6">
    <input id="firstname" name="user[firstname]" type="text" placeholder="Bob" class="form-control input-md" required="">

    </div>
  </div>

  <!-- Text input-->
  <div class="form-group">
    <label class="col-md-4 control-label" for="lastname">Last Name</label>
    <div class="col-md-6">
    <input id="lastname" name="user[lastname]" type="text" placeholder="Smith" class="form-control input-md" required="">

    </div>
  </div>

  <!-- Text input-->
  <div class="form-group">
    <label class="col-md-4 control-label" for="email">Email Address</label>
    <div class="col-md-6">
    <input id="email" name="user[email]" type="text" placeholder="bob@bob.com" class="form-control input-md" required="">

    </div>
  </div>

  <!-- Password input-->
  <div class="form-group">
    <label class="col-md-4 control-label" for="password_plaintext">Password</label>
    <div class="col-md-6">
      <input id="password_plaintext" name="password_plaintext" type="password" placeholder="" class="form-control input-md" required="">

    </div>
  </div>

  <!-- Button -->
  <div class="form-group">
    <label class="col-md-4 control-label" for="login"></label>
    <div class="col-md-4">
      <button id="login" name="login" class="btn btn-primary">Save</button>
    </div>
  </div>

  </fieldset>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <legend>Edit User</legend>
  <p>Nothing's supposed to be here yet.</p>
</div>
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">
   <center>
    <div class="page-header">
      <h1>All users</h1>
    </div>
    <div class="row">
      <% @users.each do |user| %>
      <div class="col-md-4">
        <h5><%= link_to "#{user.firstname + " " + user.lastname}", user_path(user) %></h5>
        <p><%= user.is_admin? ? "Administrator" : "Customer" %></p>
        <p><%= user.email %></p>
        <% if user.is_admin? %>
          <%= form_for :user, :url => { :action => 'make_customer', params: {id: user.id} } do |f| %>
          <% if user == current_user %>
          <p><%= f.submit "Make Customer", class: "btn btn-xs btn-inverse", disabled: true, data: { confirm: 'Are you sure you want to make this user a customer?' } %></p>
          <% else %>
          <p><%= f.submit "Make Customer", class: "btn btn-xs btn-primary", data: { confirm: 'Are you sure you want to make this user a customer?' } %></p>
          <% end %>
          <% end %>
        <% else %>
          <%= form_for :user, :url => { :action => 'make_admin', params: {id: user.id} } do |f| %>
          <p><%= f.submit "Make Administrator", class: "btn btn-xs btn-danger", data: { confirm: 'Are you sure you want to make this user an administrator?' } %><% end %></p>
        <% end %>
        <hr>
      </div>
      <% end %>
      <hr>
    </div>
  </center>
</div>

app/views/users/new.html.erb
<div class="container">
  <% if @user.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited your account from being created:</h3>
    </div>
    <div class="panel-body">
      <%= @user.errors.full_messages.join(", ") %>
    </div>
  </div>
  <% end %>
  <legend>New User Registration</legend>
  <%= render 'users/form' %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @user.firstname %>'s Profile</h3>
    </div>
    <div class="panel-body">
      <% if current_user == @user %>
      <p>This is your profile</p>
      <% else %>
      <p>This is the public profile for <%= @user.firstname %>.</p>
      <% end %>
    </div>
  </div>
</div>